### PR TITLE
feat: online count

### LINKED ISSUE #4: feat: online user count

### PR DESCRIPTION
**Pull request by hytracer**
Didn't push to main directly since i think that me and @noahpistilli are unsure if we should put it inside of wwfc or on a top-layer server, needs to be discussed before merging
Closes #4

### CODE REVIEW

**Comment by mkwcat** [comment]
In the end I think we would just want an API that could be accessed from the frontend website

**Comment by hytracer** [comment]
> In the end I think we would just want an API that could be accessed from the frontend website

We could reverse proxy it. I don't see it as doable directly in the web repo because 
1. web is in node
2. we cant interact with server directly 
3. it would be slower than handling it directly in wwfc

**Comment by hytracer** [comment]
My view on this is to run it on wwfc (or a top layer server) and reverse proxy it on site

**Comment by hytracer** [comment]
Merging this after internal discussions, might revert if we decide to use another approach in the future

**Pull request merged**
