### PR TITLE
Add build CI GitHub Actions workflow

### PR DESCRIPTION
**Pull request by ItsNiceCraft**
This PR adds a simple GitHub Actions workflow to run on push to the main branch that builds the server application for all relevant platforms using [goreleaser](https://goreleaser.com). I'm also working on getting the workflow to run properly on pull requests, but I will PR that seperately later on. The workflow publishes the built binaries in the artifacts section. Example run: [#1](https://github.com/ItsNiceCraft/wfc-server/actions/runs/7437665326).

### CODE REVIEW

**Comment by ItsNiceCraft** [comment]
Note: you might need to give GitHub actions write permissions to the repository in the [actions tab](https://github.com/WiiLink24/wfc-server/settings/actions) (scroll down to "Workflow permissions".

**Comment by mkwcat** [comment]
> The `set-output` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/

What's the reason for this warning?

**Comment by ItsNiceCraft** [comment]
The set-output syntax is set to be deprecated sometime in the future (likely not that soon), and I tried using the newer set-output function but I was having problems with it. I'm gonna take a look into it again when I have time later today

**Comment by ItsNiceCraft** [comment]
I was able to move to the new syntax to remove the warning. See [#3](https://github.com/ItsNiceCraft/wfc-server/actions/runs/7449190538).

**Comment by mkwcat** [comment]
Alright, looks good to me!!

**Pull request merged**
